//
// Created by yawkar on 03.10.22.
//

#ifndef HSE_CPP_COURSE_2_1_SIMPLE_BUBBLE_SORT_WITH_NEW_OPERATOR_H
#define HSE_CPP_COURSE_2_1_SIMPLE_BUBBLE_SORT_WITH_NEW_OPERATOR_H
void getSeriesSortItAndPrint();
#endif //HSE_CPP_COURSE_2_1_SIMPLE_BUBBLE_SORT_WITH_NEW_OPERATOR_H
